name: Deploy dev NGINX with OpenAI API Key

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::204573508773:role/deploy-role
          aws-region: ap-northeast-2

      - name: Get OpenAI API Key from AWS Parameter Store
        id: get-secret
        run: |
          OPENAI_API_KEY=$(aws ssm get-parameter --name "/online-platform-global/properties_dev/openai_api_key" --with-decryption --query "Parameter.Value" --output text)
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> $GITHUB_ENV

      - name: Replace API Key in NGINX config
        run: |
          sed -i 's|${OPENAI_API_KEY}|'"${OPENAI_API_KEY}"'|g' nginx.conf

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: openai-proxy
          IMAGE_TAG: dev
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG